### PR TITLE
Updated Pascal VOC urls, added url to trainval VOC2012 dataset

### PR DESCRIPTION
**Pull request by raindeer**
If you could put the VOC2012 test set on AWS that would be great

### CODE REVIEW

**Comment by shjb** [comment]
Thanks for the new URLs! I don't have an AWS space for hosting the files though, maybe someone else could do that?

**Comment by raindeer** [comment]
Who is hosting https://s3.amazonaws.com/scikit-data/pascal/ ?

**Comment by shjb** [comment]
Good question!

On Wed, May 27, 2015 at 3:21 PM, Erik Rehn <notifications@github.com> wrote:

> Who is hosting https://s3.amazonaws.com/scikit-data/pascal/ ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaberg/skdata/pull/68#issuecomment-106041238>.
>

-- 
Sulfur Heron is now called Kindred. Email us @kindred.ai

**Comment by shjb** [comment]
@npinto ?

On Wed, May 27, 2015 at 3:38 PM, James Bergstra <james@kindred.ai> wrote:

> Good question!
>
> On Wed, May 27, 2015 at 3:21 PM, Erik Rehn <notifications@github.com>
> wrote:
>
>> Who is hosting https://s3.amazonaws.com/scikit-data/pascal/ ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jaberg/skdata/pull/68#issuecomment-106041238>.
>>
>
>

-- 
Sulfur Heron is now called Kindred. Email us @kindred.ai

**Comment by davidcox** [comment]
Nope, it's me.  Traveling at the moment, but will look into this when I get
back.  D

**Comment by raindeer** [comment]
@davidcox has the 2012 test dataset been added to aws yet?

**Pull request merged**
